apiVersion: v1
entries:
  checking:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-03T14:36:51.4137749Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 0ce4d4c34805b11b1783542b8a7ed818874dedd35fa46922727276d85ace9dd0
    home: www.checking.nu
    icon: www.checking.nu
    name: checking
    urls:
    - checking-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-03T14:36:51.4068596Z"
