apiVersion: v1
entries:
  checking:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-27T11:45:24.5437152Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: e09c29cef94a8d1107e2a7b6b116be35e3809f498bf7de7035624f2b7e80b8c0
    home: www.checking.nu
    icon: www.checking.nu
    name: checking
    urls:
    - checking-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-27T11:45:24.5508358Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 790f23d533d146a77ebfa029747fb23d2315c9b29e2ec9aaef90ac8bee277f79
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-27T11:45:24.5366548Z"
