apiVersion: v1
entries:
  checking:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-11T09:56:07.150973Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: bfaecbcc0bac676b4332bd82262bc9cc918dae157e78b025fd4a9b87573e930c
    home: www.checking.nu
    icon: www.checking.nu
    name: checking
    urls:
    - checking-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-11T09:56:07.1564513Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 790f23d533d146a77ebfa029747fb23d2315c9b29e2ec9aaef90ac8bee277f79
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-11T09:56:07.1438983Z"
