apiVersion: v1
entries:
  checking:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-03T14:31:48.8785445Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 8069c5ee3d2b25dd1eac697637847ae85ff57f2db092508a437475b9149b6ad1
    home: www.checking.nu
    icon: www.checking.nu
    name: checking
    urls:
    - checking-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-03T14:31:48.8920897Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 790f23d533d146a77ebfa029747fb23d2315c9b29e2ec9aaef90ac8bee277f79
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-03T14:31:48.8671274Z"
