apiVersion: v1
entries:
  checking:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-11T12:18:38.4010344Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: bd8b114a8ab89efad2af08a1bf247ae6d73f6d9a47bcad4b052f14228b2871b7
    home: www.checking.nu
    icon: www.checking.nu
    name: checking
    urls:
    - checking-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-11T12:18:38.4080317Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 790f23d533d146a77ebfa029747fb23d2315c9b29e2ec9aaef90ac8bee277f79
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-11T12:18:38.3949288Z"
